# Extra autostart processes
# exec-once = uwsm-app -- my-service
# exec-once = uwsm-app -- wayvnc --render-cursor --max-fps 30 --output DP-4 0.0.0.0 5900
exec-once = waypaper --restore
exec-once = ~/.config/waybar/scripts/update-album-art.sh
