
# NVIDIA Wayland fixes
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GL_GSYNC_ALLOWED,0
env = __GL_VRR_ALLOWED,0

# Force Hyprland to composite on the NVIDIA GPU
env = AQ_DRM_DEVICES,/dev/dri/by-path/pci-0000:01:00.0-card
